apiVersion: v1
kind: Service
metadata:
  name: {{ include "milvus.etcdServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "milvus.etcdServiceName" . }}
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "milvus.etcdServiceName" . }}
  ports:
  - name: client
    port: 2379
    targetPort: 2379
    protocol: TCP
