apiVersion: v1
kind: Secret
metadata:
  name: {{ include "milvus.minioServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "milvus.minioServiceName" . }}
    {{- include "milvus.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.minio.rootUser }}
  root-password: {{ .Values.minio.rootPassword }}
