apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "milvus.minioServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "milvus.minioServiceName" . }}
    {{- include "milvus.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize }}
  storageClassName: {{ .Values.minio.storageClass }}
