{{- range .Values.modelRegistries }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-db-secret
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "5"
type: Opaque
stringData:
  database-password: {{ .dbPassword }}
{{- end }}
