apiVersion: v2
name: model-registry
description: >
  Helm chart to deploy OpenShift AI Model Registry instances
  in the rhoai-model-registries namespace.
type: application
version: 0.1.0
appVersion: 0.1.0
