{{- if .Values.deployer.domain }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: notebook-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: notebook-ui
    app.kubernetes.io/part-of: notebook-ui
    app.kubernetes.io/managed-by: Helm
spec:
  host: notebook.{{ .Values.deployer.domain }}
  port:
    targetPort: oauth
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: notebook-ui
    weight: 100
{{- end }}
