apiVersion: v1
kind: Service
metadata:
  name: notebook-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: notebook-ui
    app.kubernetes.io/name: notebook-ui
    app.kubernetes.io/part-of: notebook-ui
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app: notebook-ui
  ports:
  # oauth-proxy port — this is what the Route points to
  - name: oauth
    port: 4180
    targetPort: 4180
    protocol: TCP
  # nginx port — internal only, oauth-proxy upstream
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
