namespace: maas-rag
llamastackUrl: "http://lsd-genai-playground-service.wksp-user1.svc.cluster.local:8321"
llamastackEmbeddingModel: "sentence-transformers/snowflake-embed"
maasBaseUrl: "https://maas.apps.cluster-ttpwl.ttpwl.sandbox962.opentlc.com"
topKResults: "5"
chunkSize: "512"

tierNamespaces:
  - maas-default-gateway-tier-free
  - maas-default-gateway-tier-premium
