FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder
WORKDIR /opt/app-root/src
COPY --chown=1001:0 package.json package-lock.json* ./
RUN npm install
COPY --chown=1001:0 . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-124:latest
COPY --from=builder /opt/app-root/src/dist /opt/app-root/src/
EXPOSE 8080
USER 1001
CMD ["nginx", "-g", "daemon off;"]
