{{- range .Values.modelRegistries }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.postgresSecretName" .name }}
  namespace: rhoai-model-registries
  labels:
    app: {{ .name }}
    app.kubernetes.io/part-of: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  database-user: {{ .dbUser | default "mlmduser" }}
  database-password: {{ .dbPassword }}
  database-name: {{ .dbName | default "model_registry" }}
{{- end }}
