{{- range .Values.builds }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .name }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .name }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .name }}:latest
  source:
    type: Dockerfile
    dockerfile: |
      FROM registry.access.redhat.com/ubi9/ubi-micro:latest AS base
      FROM python:3.11-slim AS downloader
      ARG HF_TOKEN
      ENV HF_TOKEN=${HF_TOKEN}
      RUN pip install huggingface_hub
      RUN python3 -c "from huggingface_hub import snapshot_download; snapshot_download(repo_id='{{ .huggingfaceId }}', local_dir='/models')"
      FROM base
      COPY --from=downloader /models /models
  strategy:
    type: Docker
    dockerStrategy:
      buildArgs:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-token
            key: HF_TOKEN
  resources:
    limits:
      cpu: {{ .resources.limits.cpu | quote }}
      memory: {{ .resources.limits.memory }}
    requests:
      cpu: {{ .resources.requests.cpu | quote }}
      memory: {{ .resources.requests.memory }}
{{- end }}
